[package]
name = "ohms"
version = "0.1.0"
edition = "2021"
authors = ["Damon <hat3damon@gmail.com>"]
license = "MIT"

[dependencies]
chrono = "0.4"
capstone = "0.12"

[[bin]]
name = "Ohms"
path = "ohms/master.rs"